name: WordPress Plugin Check

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  plugin-check:
    name: WordPress Plugin Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Run WordPress Plugin Check
        uses: wordpress/plugin-check-action@v1
        with:
          build-dir: "./"
          wp-version: "latest"
          include-experimental: "false"
          strict: "false"

          exclude-directories: |
            .git
            .github

          exclude-files: |
            phpstan.neon.dist
            phpstan-bootstrap.php
